# Generated by Django 3.0.1 on 2020-10-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_consejeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='estado',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tema',
            name='estado',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testimonios',
            name='estado',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tips',
            name='estado',
            field=models.SmallIntegerField(default=1),
        ),
    ]
