# Generated by Django 3.0.1 on 2020-12-03 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_auto_20201028_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_galeria',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
