# Generated by Django 3.0.1 on 2020-12-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_imagenes_galeria_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=350)),
                ('estudios', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
            ],
        ),
    ]
