# Generated by Django 3.0.1 on 2020-12-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_nosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Imagen del perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
