# Generated by Django 3.0.1 on 2021-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0011_politicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejeria',
            name='consejeria_user',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
