# Generated by Django 3.0.1 on 2021-01-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0012_consejeria_consejeria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consejeria',
            name='consejeria_user',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
