# Generated by Django 3.0.1 on 2021-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0013_auto_20210130_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consejeria',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='estado',
            field=models.SmallIntegerField(default=0),
        ),
    ]
